# Generated by Django 2.2.14 on 2020-11-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='additional_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
