# Generated by Django 2.2.14 on 2020-11-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_additional_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='additional_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
