# Generated by Django 2.2.14 on 2020-11-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201106_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='item',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
